#!/usr/bin/env bash
# Install the pre-commit hook for tmux-trainsh.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK_PATH" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
exec bash scripts/pre-commit-check.sh
HOOK

chmod +x "$HOOK_PATH"
echo "Installed pre-commit hook: $HOOK_PATH"
