# tmux-trainsh config command
# Configuration management

import sys
from typing import Optional, List

from ..cli_utils import prompt_input

usage = '''[subcommand] [args...]

Subcommands:
  show             - Show current configuration
  get <key>        - Get a config value (e.g., vast.default_disk_gb)
  set <key> <val>  - Set a config value
  reset            - Reset to default configuration
  tmux-setup       - Apply tmux configuration to ~/.tmux.conf
  tmux-add <opt>   - Add a tmux option (e.g., "set -g mouse on")
  tmux-remove <n>  - Remove tmux option by index (0-based)
  tmux-list        - List all tmux options with indices

Examples:
  train config get ui.currency
  train config set ui.currency CNY
  train config tmux-setup
  train config tmux-list
  train config tmux-add "set -g status-style bg=blue"
  train config tmux-remove 5
'''


def cmd_show(args: List[str]) -> None:
    """Show current configuration."""
    from ..config import load_config

    config = load_config()

    def print_dict(d: dict, indent: int = 0):
        prefix = "  " * indent
        for key, value in d.items():
            if isinstance(value, dict):
                print(f"{prefix}{key}:")
                print_dict(value, indent + 1)
            else:
                print(f"{prefix}{key} = {value}")

    print("Current configuration:")
    print("-" * 40)
    print_dict(config)


def cmd_get(args: List[str]) -> None:
    """Get a config value."""
    if not args:
        print("Usage: train config get <key>")
        print("Example: train config get ui.currency")
        sys.exit(1)

    from ..config import get_config_value

    key = args[0]
    value = get_config_value(key)

    if value is None:
        print(f"Key not found: {key}")
        sys.exit(1)

    print(value)


def cmd_set(args: List[str]) -> None:
    """Set a config value."""
    if len(args) < 2:
        print("Usage: train config set <key> <value>")
        print("Example: train config set ui.currency CNY")
        sys.exit(1)

    from ..config import set_config_value

    key = args[0]
    value = " ".join(args[1:])

    # Type conversion
    if value.lower() == "true":
        value = True
    elif value.lower() == "false":
        value = False
    elif value.isdigit():
        value = int(value)
    else:
        try:
            value = float(value)
        except ValueError:
            pass  # Keep as string

    set_config_value(key, value)
    print(f"Set {key} = {value}")


def cmd_reset(args: List[str]) -> None:
    """Reset to default configuration."""
    confirm = prompt_input("Reset all settings to defaults? (y/N): ")
    if confirm is None or confirm.lower() != "y":
        print("Cancelled.")
        return

    from ..config import save_config, get_default_config

    save_config(get_default_config())
    print("Configuration reset to defaults.")


def generate_tmux_conf(tmux_options: list) -> str:
    """Generate tmux.conf content from options list."""
    lines = [
        "# Generated by tmux-trainsh",
        "# Edit via: train config set tmux.options '[...]'",
        "# Or edit ~/.config/tmux-trainsh/config.toml directly",
        "",
    ]
    lines.extend(tmux_options)
    return "\n".join(lines)


def cmd_tmux_setup(args: List[str]) -> None:
    """Apply tmux configuration to ~/.tmux.conf."""
    import os
    from pathlib import Path
    from ..config import load_config

    config = load_config()
    tmux_config = config.get("tmux", {})
    tmux_options = tmux_config.get("options", [])

    if not tmux_options:
        print("No tmux options found. Using defaults.")
        from ..config import get_default_config
        tmux_options = get_default_config().get("tmux", {}).get("options", [])

    tmux_conf_path = Path(os.path.expanduser("~/.tmux.conf"))
    tmux_conf_content = generate_tmux_conf(tmux_options)

    # Check if file exists and show diff
    if tmux_conf_path.exists():
        existing = tmux_conf_path.read_text()
        if existing == tmux_conf_content:
            print("tmux configuration is already up to date.")
            return

        print("Current ~/.tmux.conf will be replaced.")
        print("\nNew configuration:")
        print("-" * 40)
        print(tmux_conf_content)
        print("-" * 40)

        confirm = prompt_input("\nApply this configuration? (y/N): ")
        if confirm is None or confirm.lower() != "y":
            print("Cancelled.")
            return

        # Backup existing file
        backup_path = tmux_conf_path.with_suffix(".conf.bak")
        tmux_conf_path.rename(backup_path)
        print(f"Backed up existing config to {backup_path}")
    else:
        print("New configuration:")
        print("-" * 40)
        print(tmux_conf_content)
        print("-" * 40)

        confirm = prompt_input("\nCreate ~/.tmux.conf with this configuration? (y/N): ")
        if confirm is None or confirm.lower() != "y":
            print("Cancelled.")
            return

    # Write new config
    tmux_conf_path.write_text(tmux_conf_content)
    print(f"\nWritten to {tmux_conf_path}")
    print("\nTo apply changes, run: tmux source-file ~/.tmux.conf")
    print("Or restart tmux.")


def cmd_tmux_list(args: List[str]) -> None:
    """List all tmux options with indices."""
    from ..config import load_config, get_default_config

    config = load_config()
    tmux_options = config.get("tmux", {}).get("options", [])

    if not tmux_options:
        tmux_options = get_default_config().get("tmux", {}).get("options", [])

    print("Tmux options:")
    print("-" * 50)
    for i, opt in enumerate(tmux_options):
        print(f"  [{i}] {opt}")
    print("-" * 50)
    print(f"Total: {len(tmux_options)} options")


def cmd_tmux_add(args: List[str]) -> None:
    """Add a tmux option."""
    if not args:
        print("Usage: train config tmux-add <option>")
        print('Example: train config tmux-add "set -g status-style bg=blue"')
        sys.exit(1)

    from ..config import load_config, save_config, get_default_config

    option = " ".join(args)
    config = load_config()

    if "tmux" not in config:
        config["tmux"] = {}
    if "options" not in config["tmux"]:
        config["tmux"]["options"] = get_default_config().get("tmux", {}).get("options", [])

    config["tmux"]["options"].append(option)
    save_config(config)
    print(f"Added: {option}")
    print(f"Total options: {len(config['tmux']['options'])}")


def cmd_tmux_remove(args: List[str]) -> None:
    """Remove a tmux option by index."""
    if not args:
        print("Usage: train config tmux-remove <index>")
        print("Use 'train config tmux-list' to see indices")
        sys.exit(1)

    from ..config import load_config, save_config, get_default_config

    try:
        index = int(args[0])
    except ValueError:
        print(f"Invalid index: {args[0]}")
        sys.exit(1)

    config = load_config()
    tmux_options = config.get("tmux", {}).get("options", [])

    if not tmux_options:
        tmux_options = get_default_config().get("tmux", {}).get("options", [])
        config["tmux"] = {"options": tmux_options}

    if index < 0 or index >= len(tmux_options):
        print(f"Index out of range: {index} (valid: 0-{len(tmux_options) - 1})")
        sys.exit(1)

    removed = tmux_options.pop(index)
    config["tmux"]["options"] = tmux_options
    save_config(config)
    print(f"Removed: {removed}")
    print(f"Remaining options: {len(tmux_options)}")


def main(args: List[str]) -> Optional[str]:
    """Main entry point for config command."""
    if not args or args[0] in ("-h", "--help", "help"):
        print(usage)
        return None

    subcommand = args[0]
    subargs = args[1:]

    commands = {
        "show": cmd_show,
        "get": cmd_get,
        "set": cmd_set,
        "reset": cmd_reset,
        "tmux-setup": cmd_tmux_setup,
        "tmux-list": cmd_tmux_list,
        "tmux-add": cmd_tmux_add,
        "tmux-remove": cmd_tmux_remove,
    }

    if subcommand not in commands:
        print(f"Unknown subcommand: {subcommand}")
        print(usage)
        sys.exit(1)

    commands[subcommand](subargs)
    return None


if __name__ == "__main__":
    main(sys.argv[1:])
elif __name__ == "__doc__":
    cd = sys.cli_docs  # type: ignore
    cd["usage"] = usage
    cd["help_text"] = "Configuration management"
    cd["short_desc"] = "Manage train configuration"
